info:
  description: Api
  contact:
    name: Api
tags:
  - name: ""
    description: ""
paths:
  /data1/1:
    post:
      tags:
        - "tag1"
  /data2/2:
    post:
      tags:
        - "tag2"
  /data3/3:
    post:
      tags:
        - "tag3"